version: 0.2

env:
  variables:
    ENVIRONMENT: "dev"
    TERRAFORM_VERSION: 1.7.0

cache:
  paths:
    - /usr/bin/terraform
    - /root/.terraform.d/plugin-cache

phases:
  pre_build:
    commands:
      - echo "Pre-build phase"
      - echo "Installing Terraform version ${TERRAFORM_VERSION}..."
      - dnf install -y dnf-utils
      - dnf config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - dnf list available | grep hashicorp
      - dnf -y install terraform-${TERRAFORM_VERSION}-1.x86_64

  build:
    commands:
      - echo "Changing the directory to the deployment path..."
      - echo "Initializing Terraform..."
      - terraform init -backend-config=dev.tfbackend
      - terraform plan --var-file="dev.tfvars" -out=tfplan
      - terraform apply -auto-approve tfplan

      - |
        echo "========================================"
        echo "🎉 TERRAFORM DEPLOYMENT COMPLETED! 🎉"
        echo "========================================"
        echo "✅ Service: Splunk Lambda"
        echo "✅ Environment: $ENVIRONMENT"
        echo "✅ Timestamp: $(date)"
        echo "========================================"